### ISSUE TITLE
Implement usage of TypeScript path mappings

### ISSUE THREAD

**Issue by MaxReimerNielsen** [MartinSvarrer/sitecore-ui#7]
We would like to use the Alias property in Webpack, but it is not supported in TypeScript 1.8.

In TypeScript 2.0 they should add a feature called Path mapping, which should allow us to do import statement like this:

```ts
import Button from 'sitecore-ui/Button';
```

Where as right now we write:
```ts
import Button from '../../src/Button';
```

### Read more
[TypeScript Roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap)
[TypeScript Path mappings](https://github.com/Microsoft/TypeScript/issues/5039)
[Webpack resolve.alias](http://webpack.github.io/docs/configuration.html#resolve-alias)

**Comment by MartinSvarrer** [comment]
Will close as we decided to not move forward with TypeScript.
